# Generated by Django 5.1.5 on 2025-03-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
