# Generated by Django 5.1.5 on 2025-03-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('units', models.CharField(max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('tran_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('roundoff', models.DecimalField(decimal_places=2, max_digits=14)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
