# Generated by Django 5.1.5 on 2025-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_client_date_of_birth_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
