# Generated by Django 5.1.5 on 2025-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='truck_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='truck_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='weight',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
