# Generated by Django 5.2.1 on 2025-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_truck_number_remove_order_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='truck_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True),
        ),
    ]
